NBAjesrseyShop/NBAjesrseyShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

NBAjesrseyShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('<int:product_variant_id>/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('update/<int:product_variant_id>/', views.cart_update, name='cart_update'),
    path('remove/<int:product_variant_id>/', views.cart_remove_product,
                                     name='cart_remove_product'),
]

NBAjesrseyShop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_create, name='order_create'),
    path('created/<int:order_id>/', views.order_created, name='order_created'),
    path('user_orders/', views.user_orders, name='user_orders'),
]

NBAjesrseyShop/shop/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', HomeViews.as_view(), name='home'),
    path('team_products/<pk>', TeamProductsListViews.as_view(), name='team_products'),
    path('product_details/<pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_details/<pk>/<is_out_of_stock>/<product_variant_id>', ProductDetailView.as_view(), name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NBAjesrseyShop/cart/forms.py
from django import forms
from shop.models import ProductVariant


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)
    size = forms.ChoiceField(
                        choices=[],
                        required=True)

    def __init__(self, *args, **kwargs):
        product_id = kwargs.pop('product_id', None)
        super(CartAddProductForm, self).__init__(*args, **kwargs)

        if product_id:
            product_variants = ProductVariant.objects.filter(product_id=product_id, stock_quantity__gt=0)
            size_choices = [(variant.id, variant.size) for variant in product_variants]
            self.fields['size'].choices = size_choices


class CartUpdateProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=[],
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)
    
    def __init__(self, *args, **kwargs):
        product_variant_id = kwargs.pop('product_variant_id', [])
        product_variant = ProductVariant.objects.get(id=product_variant_id)
        super(CartUpdateProductForm, self).__init__(*args, **kwargs)

        if product_variant.stock_quantity < 10:
            quantity_choices = [(i, str(i)) for i in range(1, product_variant.stock_quantity + 1)]
        else:
            quantity_choices = [(i, str(i)) for i in range(1, 11)]
        
        self.fields['quantity'].choices = quantity_choices

NBAjesrseyShop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product, ProductVariant
from .cart import Cart
from .forms import CartAddProductForm, CartUpdateProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST, product_id=product_id)
    is_out_of_stock = False

    if form.is_valid():
        cd = form.cleaned_data
        product_variant = get_object_or_404(ProductVariant, id=int(cd['size']))
        total_quantity = cart.quantity_by_product(product_variant) + cd['quantity']

        if  total_quantity <= product_variant.stock_quantity:
            cart.add(product=product,
                    product_variant=product_variant,
                    quantity=cd['quantity'],
                    override_quantity=cd['override'])
        else:
            is_out_of_stock = True
            return redirect('shop:product_detail', pk = product_id, 
                            is_out_of_stock=is_out_of_stock, 
                            product_variant_id=product_variant.id)
    
    return redirect('cart:cart_detail')


@require_POST
def cart_update(request, product_variant_id):
    cart = Cart(request)
    form = CartUpdateProductForm(request.POST, product_variant_id=product_variant_id)

    if form.is_valid():
        cd = form.cleaned_data
        product_variant = get_object_or_404(ProductVariant, id=product_variant_id)
        cart.add(product=product_variant.product_id,
                    product_variant=product_variant,
                    quantity=cd['quantity'],
                    override_quantity=cd['override'])
        
    return redirect('cart:cart_detail')


@require_POST
def cart_remove_product(request, product_variant_id):
    cart = Cart(request)
    product= get_object_or_404(ProductVariant, id=product_variant_id)
    cart.remove_product(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    
    for item in cart:
        item['update_quantity_form'] = CartUpdateProductForm(initial={
                            'quantity': item['quantity'],
                            'override': True}, 
                            product_variant_id = item['product_variant_id'] )
    
    return render(request, 'cart_detail.html', {'cart': cart})

NBAjesrseyShop/cart/templates/cart_detail.html
{% extends "base.html" %}

{% block title %}
Your shopping cart
{% endblock %}

{% block content %}
<div class="mt-5">

    <h1>Your shopping cart</h1>

    <table class="table table-hover">
        <thead>
        <tr>
            <th>Image</th>
            <th>Jersey</th>
            <th>Size</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a>
                    <img src={{ product.image.url }} style="width: 5rem;">
                </a>
            </td>
            <td>{{ product.product_name }}</td>
            <td>{{ item.size }}</td>
            <td>
                <form action="{% url 'cart:cart_update' item.product_variant_id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <button type="submit" class="btn btn-secondary">Update</button>
                    {% csrf_token %}
                </form>
            </td>
            <td>
                <form action="{% url 'cart:cart_remove_product' item.product_variant_id %}" method="post">
                    <button type="submit" class="btn btn-danger">Remove</button>
                    {% csrf_token %}
                </form>
            </td>
            <td class="num">{{ item.product.price }} €</td>
            <td class="num">{{ item.total_price }} €</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="5"></td>
            <td class="num"><strong>{{ cart.get_total_price }} €</strong></td>
        </tr>
        </tbody>
    </table>
    <div class="row justify-content-between">
        <a class="col-6" href="{% url 'shop:home' %}">
            <button class="btn btn-secondary">Continue shopping</button>
        </a>
        {% if cart %}
        <a class="col-6 text-end" href="{% url 'orders:order_create' %}">
            <button class="btn btn-success">Go to order</button>
        </a>
        {% endif %}
    </div>

</div>
{% endblock %}