NBAjesrseyShop/NBAjesrseyShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

NBAjesrseyShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('<int:product_variant_id>/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('update/<int:product_variant_id>/', views.cart_update, name='cart_update'),
    path('remove/<int:product_variant_id>/', views.cart_remove_product,
                                     name='cart_remove_product'),
]

NBAjesrseyShop/shop/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', HomeViews.as_view(), name='home'),
    path('team_products/<pk>', TeamProductsListViews.as_view(), name='team_products'),
    path('product_details/<pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_details/<pk>/<is_out_of_stock>/<product_variant_id>', ProductDetailView.as_view(), name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NBAjesrseyShop/shop/models.py
from django.db import models


class Team(models.Model):
    team = models.CharField(max_length=50)
    team_image = models.ImageField(upload_to='images/', blank=True)

    def __str__(self):
        return f'{self.team}'


class NbaPlayer(models.Model):
    nba_player = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.nba_player}'


class Product(models.Model):
    product_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="images/", blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(blank=True)
    team_id = models.ForeignKey(Team, on_delete=models.DO_NOTHING, blank=True)
    nba_player = models.ForeignKey(NbaPlayer, on_delete=models.DO_NOTHING, blank=True)

    def __str__(self):
        return f'{self.product_name}'


class ProductVariant(models.Model):
    size = models.CharField(max_length=20)
    stock_quantity = models.PositiveIntegerField(default=0)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.product_id.product_name} | Size: {self.size} | Stock quantity: {self.stock_quantity}'
    

NBAjesrseyShop/shop/views.py
from django.shortcuts import render
from .models import *
from django.views.generic import *
from cart.forms import CartAddProductForm


class HomeViews(TemplateView):
    template_name = "home.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['teams'] = Team.objects.all()
        context['products'] = Product.objects.filter(
            productvariant__stock_quantity__gt=0).distinct()
        return context


class TeamProductsListViews(ListView):
    model = Product
    template_name = "team_products.html"
    context_object_name = 'products'

    def get_queryset(self):
        team_id = self.kwargs['pk']
        return Product.objects.filter(team_id=team_id,
        productvariant__stock_quantity__gt=0).distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team_id = self.kwargs['pk']
        context['team'] = Team.objects.get(id=team_id)
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'detail_product.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)

            is_out_of_stock = bool(self.kwargs.get('is_out_of_stock', False))
            product_variant_id = self.kwargs.get('product_variant_id')

            player = context['product'].nba_player
            team = context['product'].team_id
            cart_product_form = CartAddProductForm(product_id=context['product'].id)

            context.update({
                'player': player,
                'team': team,
                'cart_product_form': cart_product_form,
                'is_out_of_stock': is_out_of_stock,
            })

            if product_variant_id:
                try:
                    product_variant = ProductVariant.objects.get(id=product_variant_id)
                    context['product_variant'] = product_variant
                except ProductVariant.DoesNotExist:
                    pass

            return context

NBAjesrseyShop/shop/templates/detail_product.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">

            <img src="{{ product.image.url }}" alt="{{ product }} Image" style="width: 40rem;"/>
        </div>
        <div class="col">
            <h1>{{ product }}</h1>
            <p>Description: {{ product.description }}</p>
            <p>Player: {{ player }}</p>
            <strong>Price: {{ product.price }} €</strong>
            {% if is_out_of_stock %}
            <p class="text-danger">Sorry, this product is out of stock. 
                Only {{ product_variant.stock_quantity }} pieces available 
                in size {{product_variant.size}}.</p>
            {% endif %}
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-cart"></i><span class="ms-2">Add to cart</span>
                </button>
            </form>
            <p>
                <a href="{% url 'shop:team_products' team.pk %}">
                <button class="btn btn-secondary mt-3">{{team}} Jerseys</button>
                </a>
            </p>
            <p>
                <a href="{% url 'shop:home' %}">
                    <button class="btn btn-secondary">Back to shop</button>
                </a>
            </p>
        </div>
    </div>
</div>

{% endblock content %}

NBAjesrseyShop/shop/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div class="mt-5">

        <h2>Teams</h2>
        <ul class="mt-3">
            {% for team in teams %}
            {% if team.team_image %}
            <a href="{% url 'shop:team_products' team.pk %}" class="me-2">
                <img src="{{ team.team_image.url }}" alt="{{ team.team }} Image" class="hover img-fluid" width="70">
            </a>
            {% endif %}
            {% endfor %}
        </ul>
    </div>

    <div class="mt-5">
        <h2>Jerseys</h2>
        <div class="container mt-3">
            <div class="row">
                {% for product in products %}

                <div class="card hover" style="width: 20rem;">
                    <a href="{% url 'shop:product_detail' product.pk %}">
                        <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product }} Image">

                        <div class="card-body">
                            <h6 class="card-title">{{ product }}</h6>
                            <p class="card-text">{{ product.price }} €</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>



{% endblock content %}

NBAjesrseyShop/shop/templates/team_products.html
{% extends 'base.html' %}

{% block content %}
<div class="mt-5">
  <a href="{% url 'shop:home' %}">
    <button class="btn btn-secondary">Back to shop</button>
  </a>
  <h2 class="mt-4">
    <img src="{{ team.team_image.url }}" alt="{{ team.team }} Image" style="max-width: 40px;">
    {{ team.team}} Jerseys
  </h2>
  
  {% if products %}
  <div class="container mt-3">
      <div class="row">
          {% for product in products %}
          <div class="card hover" style="width: 20rem;">
              <a href="{% url 'shop:product_detail' product.pk %}">
              <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product }} Image">
          
              <div class="card-body">
                  <h6 class="card-title">{{ product }}</h6>
                  <p class="card-text">{{ product.price }} €</p>
              </div>
              </a>
          </div>
          {% endfor %}
      </div>
  </div>
  {% else %}
    <div>
        <p>There are no products for this team.</p>
    </div>
  {% endif %}
</div>
{% endblock content %}