NBAjesrseyShop/NBAjesrseyShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

NBAjesrseyShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('<int:product_variant_id>/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('update/<int:product_variant_id>/', views.cart_update, name='cart_update'),
    path('remove/<int:product_variant_id>/', views.cart_remove_product,
                                     name='cart_remove_product'),
]

NBAjesrseyShop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_create, name='order_create'),
    path('created/<int:order_id>/', views.order_created, name='order_created'),
    path('user_orders/', views.user_orders, name='user_orders'),
]

NBAjesrseyShop/shop/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', HomeViews.as_view(), name='home'),
    path('team_products/<pk>', TeamProductsListViews.as_view(), name='team_products'),
    path('product_details/<pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_details/<pk>/<is_out_of_stock>/<product_variant_id>', ProductDetailView.as_view(), name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NBAjesrseyShop/orders/models.py
from django.db import models
from accounts.models import Address
from shop.models import ProductVariant


class Order(models.Model):
    order_date = models.DateTimeField(auto_now_add=True)
    payment_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=20,default="placed")
    total_cost = models.DecimalField(max_digits=8, decimal_places=2)
    address_id = models.ForeignKey(Address, on_delete=models.DO_NOTHING, blank=True)

    def __str__(self):
        return f'Order id: {self.id} | {self.address_id.user_id} | Order date: {self.order_date} | Total cost: {self.total_cost} | Status: {self.status}'
    

class OrderProducts(models.Model):
    quantity = models.IntegerField()
    product_by_quan_coast = models.DecimalField(max_digits=8, decimal_places=2)
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    product_variant_id = models.ForeignKey(ProductVariant, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f'Order id: {self.order_id.id} | Order by: {self.order_id.address_id.user_id} | {self.product_variant_id.product_id} | Quan: {self.quantity} | Total cost: {self.product_by_quan_coast}'

NBAjesrseyShop/orders/views.py
from django.shortcuts import render, get_object_or_404
from .models import OrderProducts, Order
from shop.models import ProductVariant
from accounts.models import Address
from cart.cart import Cart
from collections import defaultdict
from django.shortcuts import redirect
from django.urls import reverse_lazy


def order_create(request):
    user = request.user
    
    if user.id:
        cart = Cart(request)
        address = get_object_or_404(Address, user_id=user.id, 
                                default_shipping_address=True)
        
        if request.method == 'POST':
            total_cost = cart.get_total_price()
            order = Order.objects.create(total_cost=total_cost, address_id=address)
            
            for item in cart:
                product_variant = get_object_or_404(ProductVariant, 
                                                    id=item['product_variant_id'])
                OrderProducts.objects.create(order_id=order,
                                        product_variant_id=product_variant,
                                        quantity=item['quantity'],
                                        product_by_quan_coast=item['total_price'])
                product_variant.stock_quantity -= item['quantity']
                product_variant.save()

            cart.clear()
            return redirect('orders:order_created', order_id=order.id)
    
    else:
        return redirect(reverse_lazy('login') + ('?next=orders:order_create'))
    
    return render(request,
                  'order_create.html',
                  {'cart': cart, 'user': user, 'address': address})


def order_created(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order_created.html', {'order': order})


def user_orders(request):
    user = request.user
    address = get_object_or_404(Address, user_id=user.id)
    orders = Order.objects.filter(address_id=address.id).order_by('-order_date')
    orders_by_date = defaultdict(lambda: {'order_id': None, 'products':[], 'total_cost':0})
    
    for order in orders:
        order_products = OrderProducts.objects.filter(order_id=order)
        orders_by_date[order.order_date]['order_id'] = order.id
        
        for order_product in order_products:
            product_name = order_product.product_variant_id.product_id.product_name
            orders_by_date[order.order_date]['products'].append({
                'product_name': product_name,
                'quantity': order_product.quantity,
                'size': order_product.product_variant_id.size,
                'product_by_quan_coast': order_product.product_by_quan_coast,
            })
        
        orders_by_date[order.order_date]['total_cost'] = order.total_cost
    orders_info = [{'order_date': order_date, **data} for order_date, data in
                     orders_by_date.items()]
    
    return render(request, 'user_orders.html', {'orders_info': orders_info})

NBAjesrseyShop/orders/templates/order_create.html
{% extends 'base.html' %}

{% block content %}
<div class="mt-5">

    <h1>Checkout</h1>
    <div class="container pt-2">
        <div class="row">
            <div class="col-7">
                <table class="table">
                    <thead>
                        <tr>
                          <th></th>
                          <th>Jersey</th>
                          <th>Size</th>
                          <th>Price</th>
                        </tr>
                    </thead>
                    {% for item in cart %}
                    {% with product=item.product %}
                    <tr>
                        <td><img src={{ product.image.url }} style="width: 5rem;"></td>
                        <td>{{ item.quantity }} x {{ item.product }}</td>
                        <td>{{item.size}}</td>
                        <td>{{ item.total_price }} €</td>
                    </tr>
                    {% endwith %}
                    {% endfor %}
                </table>
                <p class="text-end"><strong>Total cost: {{ cart.get_total_price }} €</strong></p>
            </div>

            <div class="col-4 offset-1">
                <h3>Shipping information</h3>
                <p>Name: {{ user }}</p>
                <p>Address: {{ address }}</p>
            </div>
        </div>
        <div class="row justify-content-between">
            <a class="col-6" href="{% url 'cart:cart_detail' %}">
                <button class="btn btn-secondary">Back To Cart</button>
            </a>
            <div class="col-6 text-end">
                {% if cart %}
                <form method="post">
                    <button type="submit" class="btn btn-success">Place order</button>
                    {% csrf_token %}
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

NBAjesrseyShop/orders/templates/order_created.html
{% extends "base.html" %}

{% block title %}
  Thank you
{% endblock %}

{% block content %}
<div class="mt-5">

  <h1>Thank you</h1>
  <p>Your order has been successfully completed. Your order number is
  <strong>{{ order.id }}</strong>.</p>

  <a href="{% url 'shop:home' %}">
    <button class="btn btn-secondary">Back to shop</button>
  </a>
</div>
{% endblock %}

NBAjesrseyShop/orders/templates/orders.html
{% extends 'base.html' %}

{% block content %}
<h1>Checkout</h1>

<div class="order-info">
  <h3>Shipping information</h3>
  <p>Name: {{ user }}</p>
  <p>Address: {{ address }}</p>

  <h3>Your order</h3>
  <ul>
    {% for item in cart %}
    {% with product=item.product %}
      <li>
        <a><img src={{ product.image.url }} style="width: 5rem;"></a>
        {{ item.quantity }}x {{ item.product }}
        <span>{{ item.total_price }} €</span>
      </li>
    {% endwith %}
    {% endfor %}
  </ul>
  <p>Total: ${{ cart.get_total_price }} €</p>
</div>
<form method="post" class="order-form">
  <p><input type="submit" value="Place order"></p>
  {% csrf_token %}
</form>

{% endblock content %}

NBAjesrseyShop/orders/templates/user_orders.html
{% extends "base.html" %}


{% block content %}
<div class="mt-5">
    <a href="{% url 'shop:home' %}">
        <button class="btn btn-secondary">Back to shop</button>
    </a>
    <div class="mt-4">
        {% if orders_info %}
        <h2><span class="text-success">{{user.first_name}} {{user.last_name}}</span> orders:</h2>

        {% for order_info in orders_info %}
        <div class="pt-3">
            <div class="row">
                <h4 class="col-6">Order no.: {{ order_info.order_id }}</h4>
                <span class="col-6 text-end">{{ order_info.order_date }}</span>
            </div>
            <ul>
                {% for product_info in order_info.products %}
                <li>
                    Product Name: {{ product_info.product_name }}<br>
                    Quantity: {{ product_info.quantity }}<br>
                    Size:  {{product_info.size}}<br>
                    Product by quantity cost: {{ product_info.product_by_quan_coast }} €<br>
                </li>
                {% endfor %}
            </ul>
            <h4 class="text-end">Total cost: {{ order_info.total_cost }} €</h4>
            <hr>
        </div>
        {% endfor %}
        {% else %}
        <h2>There are no orders for {{user.first_name}} {{user.last_name}}</h2>
        {% endif %}
    </div>
</div>
{% endblock content %}